### ISSUE TITLE
Update FR sync to accept a tag representing the EntitySource and tags representing downstream metadata instances

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/saml-service#117]
Right now we simply take in 'aaf' and use this to:
1. Look up an EntitySource
2. Tag created/updated entities with 'aaf' so it flows to our metadata documents

What we should do is look up an EntitySource of something like 'aaf-fr' and then tag created/updated entities with this AND extra provided tags, in this specific case 'aaf' to ensure automated flow through to the AAF MetadataInstance

**Comment by matthew-puku** [comment]
FR is going away
