### ISSUE TITLE
Support SIRTFI security contacts

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/saml-service#124]
https://wiki.refeds.org/display/SIRTFI/Guide+for+Federation+Operators#GuideforFederationOperators-MetadataaggregatesforSirfticompliantentities

**Comment by vladimir-mencl-eresearch** [comment]
Hi @bradleybeddoes 

And I believe this one can be closed too - appears to have been implemented in #173 and #175 .

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Thanks!
