### ISSUE TITLE
Test Nokogiri 1.6.8 which holds fix we previously manually added

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/saml-service#125]
https://github.com/sparklemotion/nokogiri/releases/tag/v1.6.8

**Comment by vladimir-mencl-eresearch** [comment]
Hi @bradleybeddoes ,

I went through the list of open issues (before filing #204) and this one looks like it can be closed - apparently resolved by 782e098)

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Thanks!
