### ISSUE TITLE
Add more options for sync_to_git.rb

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/saml-service#204]
Hi @bradleybeddoes ,

I've been looking at adding `sync_to_git.rb` to our workflow - primarily to track history of metadata we send to eduGAIN, but possibly also of metadata we get from eduGAIN.

And in that tracking, I started looking at eliminating false positives / spurious changes - that's been the driver for #203 and https://github.com/ausaccessfed/federationregistry/pull/257

I don't know if you are actually using this in your PROD workflow - if yes, I'd be keen to hear details on that (pushing to via ssh or https,...) ?

While looking at what would work for us, I see I'd need to make the file configurable (to avoid hard-coding our values in our divergent copy of the script...).

Specifically, I'd need the following configurable:
* committer identity
* credentials to use with `Rugged::Remote.push` (in our case, `SshKey`, could also include `UserPassword`)
* whether to sign per-entity RAW entity descriptors (so far, I'm getting spurious metadata changes from `ds:Reference` where the timestamp always changes).  And signatures here are just noise..

I'm thinking I'd allow passing a YAML configuration file to sync_to_git which would set all of the above - and defaults would match current behaviour/values.

Would that sound acceptable to you / would you be willing to merge such code?

At some point, our code bases would to a degree diverge, but I'm thinking this might still be useful to you too - please let me know.

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
We've not used this in any sort of production. We had a potentially case we prepared for back in 2017 but it never shipped.

Right now the script takes in parameters from the command line, I would be happy to see a PR that alters that to a single parameter pointing to a config file.

Other configuration options sound fine.

Do you have thoughts/plans around supporting static serving of MDQ? We plan to get away from anything dynamic in that space and offer up something static (at TBD future ideas are always great o'clock).

**Comment by vladimir-mencl-eresearch** [comment]
Implemented by #206
