### ISSUE TITLE
Provide non certifcate based API authentication mechanism

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/saml-service#221]
Whilst @rianniello was rolling out https://github.com/ausaccessfed/stockpile/issues/43 monitoring alerted that connections to SAML Service in test fed stopped being honoured. 

Investigation per https://github.com/ausaccessfed/stockpile/issues/49 showed that the move to AWS ALB was the root cause here as we previously had undertaken API authentication using `SSLClientVerify` at the Apache level which is no longer feasible in the model where we terminate public SSL at the ALB. Currently, we've rolled back to direct Apache connections on this service in the test federation to restore functionality.

To support our move to ALB the API here needs to be extended to also accept a token via header/query param to permit remote services access when ALB is re-instated.

Token values should be unique per `APISubject`, requiring an extension of the underpinning schema.

**Comment by bradleybeddoes** [comment]
Noting the deployment will require an https://github.com/ausaccessfed/aaf-ansible PR in parallel to deprecate the `SSLClientVerify` configuration in Apache.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @bradleybeddoes ,

Not sure what you exactly ran into at ALB, but FYI, when we updated to latest Apache on our Ubuntu 18.04 hosts, SSLVerfifyClient optional stopped working (as renegotiation for a specific Location (/api), when combined together with TLSv1.3.

I have reported this to Ubuntu:
- comment #26 at https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1865900
and further upstream to Apache:
https://bz.apache.org/bugzilla/show_bug.cgi?id=64263

But right now, I've ended up disabling the authenticated part of the API (we're not using it yet).

So, moving away from SSLClientVerify sounds as the very right step - I'll be keen to see the further progress here...

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Hi @bradleybeddoes ,

I have been digging into the TLSv1.3 SSLVerifyClient issues further, and found that TLSv1.3 requires all HTTPS clients to change how they invoke the API to support post-handshake authentication.  So this can be solved by updating clients ... but might be too much effort and take too much time.

And I see you've just implemented #222 - I'm looking forward to seeing it merged and simplifying our deployment.

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
> Not sure what you exactly ran into at ALB
ALB has no support for this model, at least not in the way we need it to operate without hacks and mess that we don't want.

> TLSv1.3 requires all HTTPS clients to change how they invoke the API
Also correct and painful but not the specific issue the AAF tripped over which was nice.

> I see you've just implemented #222 
Indeed, has been assigned for review, feel free to try it out.
