### ISSUE TITLE
Outdated personal version of rspec_sequel_matchers

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/saml-service#269]
Hi @rianniello ,

When reviewing #266 , I stumbled upon a line in both `Gemfile` and `Gemfile.lock` that uses a "personal version" of the `rspec_sequel_matchers` gem:
https://github.com/ausaccessfed/saml-service/blob/develop/Gemfile#L42
```
  gem 'rspec_sequel_matchers', git: 'https://github.com/bradleybeddoes/rspec_sequel_matchers.git'
```

I'd expect AAF would want to use either proper upstream repositories or forks under ausaccessfed...

I've traced this line back to commit 384e668c (8 years ago), with the commit message pointing to a [PR](https://github.com/openhood/rspec_sequel_matchers/pull/12) addressing an issue - but the PR had been merged along ago (shortly after being made) and a newer version has been released since (0.5.0, released 2 years after merging the PR), so I believe 'rspec_sequel_matchers' can be reverted back to rubygems latest - which should pick 0.5.0.

Cheers,
Vlad

**Comment by waldofouche** [comment]
Hi Vlad, 

Thanks for looking into this! I have bumped the version of `rspec_sequel_matchers` to `0.5.0` as recommended, everything is looking good so far with that change. I did not create a seperate PR, however I have added to to be released with the upgrade to rails `61.4.7` here: #267 

Thanks
