### ISSUE TITLE
Check `XSD` files into Github, instead of constantly downloading them

### ISSUE THREAD

**Issue by waldofouche** [ausaccessfed/saml-service#272]
see https://github.com/ausaccessfed/saml-service/pull/271#issuecomment-1087045621 for more info

**Comment by waldofouche** [comment]
Thoughts on this one @rianniello ?

**Comment by rianniello** [comment]
Good approach. Will make our builds a bit more stable.

**Comment by rianniello** [comment]
Could also put them into our S3 if that's easier.

**Comment by matthew-puku** [comment]
The files are pretty small. I think < 100kb in total.

**Comment by waldofouche** [comment]
Little bit more, but yeah I think s3 might be a bit overkill for them here

<img width="260" alt="Screen Shot 2022-04-04 at 10 51 05 am" src="https://user-images.githubusercontent.com/39336960/161466024-364cb40e-9340-4b87-a55c-b7bcb2fa03e0.png">

**Comment by vladimir-mencl-eresearch** [comment]
I think S3 would be tricky - you'd need to map each namespace URI to a URL to download from (... and selfishly, it would break for us without access to your S3).

Local copies as "already downloaded" would be the easiest to handle.
