### ISSUE TITLE
rspec broken

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/saml-service#281]
Hi,
Just creating a ticket to track that rspec is broken - I guess possibly do to the Rails upgrade.

RSpec has a number of tests failing for `API::APIController`.  Tests report unexpected method calls like `root`, `action_view` on an anonymous object - which I believe is the faked application config and these are just additional config entries that are now being accessed.

From the stack-traces printed by rspec, I can e.g. see that `railties` now uses `application.config.root`

I hope there would be some magic to put into rspec config instead of having to manually set up all of this in fake config objects ... but this goes beyond my knowledge of rspec, so just creating a ticket here...

Cheers,
Vlad

**Comment by phyzical** [comment]
Hey  @vladimir-mencl-eresearch,

I can confirm the rspec tests are still passing
![image](https://user-images.githubusercontent.com/5182053/170179810-4f095c20-419b-4cea-b36e-65fa1b1b6006.png)

just to confirm 
* tests are being run via `bundle exec rspec`
* You are using `2.7.4`
* Reinstalled bundle
* attempted with a fresh test DB (just in case)

**Comment by vladimir-mencl-eresearch** [comment]
Hi @phyzical , thanks for getting back to me.

Puzzling it works for you but fails to me.

So I've tried:
* a clean checkout of the `develop` branch
* Ruby `2.7.4` (install from src on Ubuntu 18.04)
* fresh `bundle install` (into a newly created `GEM_PATH` directory)
* refreshed database (drop database, create database, run `RAILS_ENV=test bundle exec rake db:schema:load`)

... and `bundle exec rspec` gave me a clean pass: `2085 examples, 0 failures`

So I started looking into why it failed for me: to get consistent results, I was running rspec with `bundle exec rspec --order fixed` - and that still returns failure for most tests under `API::APIController`:
```
API::APIController
  is expected to respond to #subject
  requesting resource that does not exist
    example at ./spec/controllers/api/api_controller_spec.rb:37 (FAILED - 1)
    responds with the exception (FAILED - 2)
  a bad request
    example at ./spec/controllers/api/api_controller_spec.rb:68 (FAILED - 3)
    responds with the exception (FAILED - 4)
  #ensure_authenticated as before_action
    invalid authentication method
      example at ./spec/controllers/api/api_controller_spec.rb:97 (FAILED - 5)
      json within response
        has a message (FAILED - 6)
    unknown authentication method
      example at ./spec/controllers/api/api_controller_spec.rb:112 (FAILED - 7)
      json within response
        has a message (FAILED - 8)
    x509 authentication
      no x509 header set by nginx
        example at ./spec/controllers/api/api_controller_spec.rb:129 (FAILED - 9)
        json within response
          has a message (FAILED - 10)
          has an error (FAILED - 11)
      x509 header set to "(null)"
        example at ./spec/controllers/api/api_controller_spec.rb:147 (FAILED - 12)
        json within response
          has a message (FAILED - 13)
          has an error (FAILED - 14)
      invalid x509 header set by nginx
        example at ./spec/controllers/api/api_controller_spec.rb:164 (FAILED - 15)
        json within response
          has a message (FAILED - 16)
          has an error (FAILED - 17)
      without a CN component to DN
        example at ./spec/controllers/api/api_controller_spec.rb:181 (FAILED - 18)
        json within response
          has a message (FAILED - 19)
          has an error (FAILED - 20)
      with a CN that does not represent an APISubject
        example at ./spec/controllers/api/api_controller_spec.rb:199 (FAILED - 21)
        json within response
          has a message (FAILED - 22)
          has an error (FAILED - 23)
    token authentication
      invalid authorization header provided by client
        example at ./spec/controllers/api/api_controller_spec.rb:222 (FAILED - 24)
        json within response
          has a message (FAILED - 25)
          has an error (FAILED - 26)
      with a token that does not represent an APISubject
        example at ./spec/controllers/api/api_controller_spec.rb:239 (FAILED - 27)
        json within response
          has a message (FAILED - 28)
          has an error (FAILED - 29)
    with an APISubject that is not functioning
      example at ./spec/controllers/api/api_controller_spec.rb:261 (FAILED - 30)
      json within response
        has a message (FAILED - 31)
        has an error (FAILED - 32)
  #ensure_access_checked as after_action
    subject without permissions
      fails request to incorrectly implemented action (FAILED - 33)
      completes request to a public action (FAILED - 34)
      has no permissions
      the request does not complete
        should respond with status code :forbidden (403) (FAILED - 35)
        recieves a json message (FAILED - 36)
    subject with invalid permissions
      fails request to incorrectly implemented action (FAILED - 37)
      completes request to a public action (FAILED - 38)
      has an invalid permission
      the request does not complete
        should respond with status code :forbidden (403) (FAILED - 39)
        recieves a json message (FAILED - 40)
    subject with x509 authentication and valid permission
      fails request to incorrectly implemented action (FAILED - 41)
      completes request to a public action (FAILED - 42)
      has a valid permission
      completes request after permissions checked (FAILED - 43)
    subject with token authentication and valid permission
      fails request to incorrectly implemented action (FAILED - 44)
      completes request to a public action (FAILED - 45)
      has a valid permission
      completes request after permissions checked (FAILED - 46)
```
I also get the same with: `bundle exec rspec --example 'API::APIController'`: `51 examples, 46 failures`

I find it puzzling why the default random order works, but these specific invocations break.

Are you able to reproduce the errors with these invocations?

Cheers,
Vlad

**Comment by phyzical** [comment]
interesting, yeah i can confirm it fails when i run  `bundle exec rspec --order fixed`,
 oddly enough it also fails with an extension i use for vscode to run tests, but always passes with a plain old `bundle exec rspec` or even a  simple `bundle exec rspec SPEC_FILENAME`

```
RSpec::Mocks::MockExpectationError:
#<Double (anonymous)> received unexpected message :action_view with (no args)
```

and can confirm in the stack trace its dieing in actionview at due to maybe a miss confirgured mock that doesn't get setup correctly when we run the test with filter arguments? (which is where the action_view call you saw in the stack trace came from i think)

https://github.com/rails/rails/blob/v6.1.6/actionview/lib/action_view/railtie.rb#L64

will do a further investigation tomorrow 👍

**Comment by phyzical** [comment]
```
def auth_type(type)
    Rails.application.config.saml_service.api.authentication = type

    # allow(Rails.application)
    #   .to receive_message_chain(:config, :saml_service, :api, :authentication)
    #   .and_return(type)
  end
  ```

 if we change the above all tests pass bar one, will investigate the last failing test when i get a chance 👍 

So probably just something to do with receive_message_chain which is not recommended these days for mocks anyway, will give it a go with a newer version of mocks and see how it goes

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the quick fix - happy to confirm it now works for me as well.
