### ISSUE TITLE
Duplicate displayName entries for IdP+SP entities

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/saml-service#368]
Hi,

I found this when troubleshooting the issue reported in https://github.com/ausaccessfed/discovery-service/pull/329

For an entity that has both an `IDPSSODescriptor` and `SPSSODescriptor`, each with a mdui:UIInfo element, the SAML Service includes duplicate `displayName`, `description` and other entries for the same language in the JSON entities feed for the Discovery Service.   This duplicate entries are taken by combining the UIInfo of the IdP and SP descriptors.

As a result, the Discovery Service presents the name of the institution twice (with only the first entry being selectable).

![Screenshot 2023-05-25 at 15 46 14](https://github.com/ausaccessfed/saml-service/assets/740558/58ad1148-a8b3-4a65-b9b7-d7b645b92692)

I've dug into it and can see this comes form how the `RawEntityDescriptorDeconstructor` (in `app/models/concerns/raw_entity_descriptor_deconstructor.rb`) defines `ui_info`: the `element_xpath()` method uses an XPath path wildcard (any path leading to an element) to get UIInfo - and so it gets it via both `IDPSSODescriptor` and `SPSSODescriptor`.

I don't see an easy fix for this without refactoring existing code: instead of being asked "What's your UIInfo`, the method would have to be reframed to "What's your UIInfo in the context of an IdP" (or SP).

Alternatively, a short-cut might be to just accept the first result found... (and letting e.g. an IdP UIInfo win over SP UIInfo - if both are present for an entity).

But given the changes / decisions required, I'm not sending a PR, just reporting it as an issue.

Please let me know if you have a preferred approach to tackling this - I'd be happy to contribute a PR.

Cheers,
Vlad

PS: To reproduce this, just go to e.g. https://cloud.rdm.uq.edu.au/, select eduGAIN to log in, and on the International tab, search for "Link" - `Linköping University` / `http://fs.liu.se/adfs/services/trust` is an example of an entity combining an IdP and SP descriptor.

**Comment by matthew-puku** [comment]
Resolved by https://github.com/ausaccessfed/discovery-service/pull/362 — sort of. SAML service is still bugged, but we don't care anymore because we don't use the endpoint.
