### ISSUE TITLE
Scope out migrating metadata instances off sha1

### ISSUE THREAD

**Issue by bo-aaf** [ausaccessfed/saml-service#371]
saml  metadata instances are still using deprecated sha1 for openssl. This needs to be migrated off sha1 to sha256 ideally

**Comment by matthew-puku** [comment]
I thought this was metadata instances, not services?

**Comment by bo-aaf** [comment]
you are right puku! Just testing you

**Comment by vladimir-mencl-eresearch** [comment]
Hi guys,  trying to follow this - which use of SHA1 is this about?

I can see that your metadata is signed with SHA256 - in https://md.aaf.edu.au/aaf-metadata.xml, I can see:
`<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>` and `<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>`.

And your metadata signing certificate advertised there also uses `sha256WithRSAEncryption` .... so just curious, what SHA1 use is this about?

**Comment by phyzical** [comment]
i think we did a quick scan of requests and found reqs like 


```
I, [2023-05-24T00:52:04.451039 #15293]  INFO -- : [9e4ce88c-2d60-42a0-a6f0-d96b3b7c49f3] method=GET path=/mdq/federation-manager/entities/%7Bsha1%7D7b51df8e123263ee0a1XXXXXXXXXX format= controller=MetadataQueryController action=specific_entity_sha1 status=200 duration=311.86 view=0.96 db=200.50 params={"instance"=>"federation-manager", "identifier"=>"{sha1}
```


and db entries for out db like 

```
{
    :id=>4, 
    :name=>"aaf.edu.au", 
    :extensions=>nil, 
    :created_at=>2016-10-05 23:13:22 UTC, 
    :updated_at=>2018-04-10 01:04:46 UTC, 
    :ca_verify_depth=>nil, 
    :hash_algorithm=>"sha1", 
    :keypair_id=>2, 
    :identifier=>"aaf-legacy", 
    :all_entities=>true, 
    :federation_identifier=>"aaflegacy", 
    :validity_period=>604800, 
    :cache_period=>21600,
    :primary_tag=>"aaflegacy"
}
```

so it may just be an issue with our data. though to be fair maybe we didnt look hard enough

@bo-aaf mind doing a bigger review of all this incase we were looking int he wrong direction?

**Comment by vladimir-mencl-eresearch** [comment]
Hi @phyzical , thanks for the context - I think you are following a false lead here.

This is not about using SHA1 in any way related to cryptography.

This is just the standard Metadata Query (MDQ) interface, which also provides a way of requesting metadata for an entity based on the SHA1 hash of its entityID.

Have a look at the section `4.2.  Use of SHA-1 in Transformed Identifiers` in the MDQ spec at https://datatracker.ietf.org/doc/draft-young-md-query-saml/

They conclude they do not see the use of SHA1 as a concern at the moment - with recommendations on treating collisions in MDQ implementations.

But without changing the MDQ specification, there is not much you'd be able to do about this....

Cheers,
Vlad

**Comment by phyzical** [comment]
@vladimir-mencl-eresearch thanks for that,

just for your context the last bit that i think wasn't mentioned is that this all stemmed from this test, 

https://github.com/ausaccessfed/saml-service/blob/master/spec/support/metadata/signature.rb#L95

So your probably right and its just a redundant test at this point. but to be safe we will have to review all data in all environments

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for that!

I see ... the `MetadataInstance` model in `app/models/metadata_instance.rb` allows `hash_algorithm` to be either `sha1` or `sha256.

The tests aim to cover all paths, so also try signing metadata with SHA1.

The actual algorithm used by a `MetadataInstance` is selected by its `hash_algorithm` - which defaults to `SHA256`, as per https://github.com/ausaccessfed/saml-service/blob/master/bin/configure.rb#L94-L95

So it should be enough for you to audit existing `MetadataInstance` instances and check their HashAlgorithm.

E.g. with:
```MetadataInstance.all { |md| puts "#{md.name} #{md.hash_algorithm}" } ; nil```

But unless it was explicitly overridden to SHA1, it should be SHA256 - the default was there from the beginning.

So maybe the right solution would be just dropping the tests for SHA1 and maybe even restricting the model for `MetadataInstance` to not allow SHA1 for `hash_algorithm` ....

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
PS: Just checked our instances: all using SHA256.
