### ISSUE TITLE
Investigate cache expiry times, metadata expiry, etc...

### ISSUE THREAD

**Issue by smangelsdorf** [ausaccessfed/saml-service#75]
Currently, the Rails cache expiry time is tied to the metadata document expiry, which is causing problems because the document can be cached multiple times per hour resulting in huge memory usage

`top` showed `redis-server` at 12.3% memory usage (out of 3500MB) when I noticed this problem. Clearing away the cached metadata documents dropped it back to 0.5% usage. The problem would multiply very quickly if we had multiple documents being generated, and especially documents with more entities.

I'd suggest a few things need investigating:

1. How long do we need to cache the metadata documents for? I'd suggest no longer than 6 hours is probably appropriate. After that point, we probably want a fresh document anyway, to refresh the metadata document expiry.
2. Is the `ETag` header affected by the metadata expiry time? Could we end up incorrectly telling somebody their document is the most recent version, when in fact there's an updated version with a new `validUntil`? (It seems likely that this is the reason documents are cached until they expire, but see the next point...)
3. At some point in the future, when FR Sync is disabled and SAML Service takes over as the authoritative source, is there a mechanism for generating a fresh document if nothing in the federation has changed?
4. The HTTP `Expires` header sent in response may need some thought... If the document is cached at an SP / IdP until it expires, and the document expiry time coincides with a network fault, fresh metadata may not be available which could disrupt service. If the expiry time were significantly shorter than the document lifetime, there would be a longer period of fault tolerance before the document expired.

**Comment by bradleybeddoes** [comment]
Thanks, good comments here.

0. This seems like a no brainer on reflection. I suggest the addition of a field to `MetadataInstance` called `cache_period` for this purpose so we can cache different metadata documents for different periods of time. 

https://github.com/ausaccessfed/saml-service/blob/develop/app/controllers/concerns/metadata_query_caching.rb#L48

    The period to cache for should probably be some kind of fraction of the existing validityPeriod. For example if the metadata document is valid for 7 days then perhaps 1 - 3 days worth of caching is reasonable? This assumes of course that metadata isn't invalidated in the interim by some change which will immediately expire the cached version anyway.

0. This shouldn't be the case. Per the following path:

    https://github.com/ausaccessfed/saml-service/blob/develop/app/controllers/metadata_query_controller.rb#L49
    https://github.com/ausaccessfed/saml-service/blob/develop/app/controllers/concerns/metadata_query_caching.rb#L19
    https://github.com/ausaccessfed/saml-service/blob/develop/app/controllers/concerns/metadata_query_caching.rb#L28

   Essentially we generate what we expect the current etag value to be from current data and compare for a match. Should there be a difference the etag is invalid and a new response document is sent (which may come from cache if some prior request has cached the new valid version of course).

   The specs back this up but I wanted to highlight the path here so it can be double checked. Let me know if you feel this doesn't correctly address the issue you where considering.

0. No. However if/when we do 1 would there be a real need for this? Worst case scenario the Redis cache could be flushed which would give the same effect. I am concerned that adding something which allows the cache to be defeated by an external query (assuming unauthenticated like the request of MDQ) could lead to a DoS scenario. Thoughts?

0. It is my understanding that most, if not all (especially Shibboleth: https://wiki.shibboleth.net/confluence/display/IDP30/MetadataConfiguration - `refreshDelayFactor`) implementations don't wait until the absolute last minute to refresh metadata. Infact I'd personally consider it a bug on the implementation side if they did. Granted this is based on the SAML MD `validUntil` field and not a `Cache-Control` header per se.

    The MDQP specification doesn't highlight the specific value that should be set for the `Cache-Control` header, just that it must be set. It might make sense for this value to be the same as that introduced in 1. Whilst I don't (currently) expect any intermediates to be caching these documents they certainly shouldn't be doing so for any longer than we are.

**Comment by smangelsdorf** [comment]
1. Agreed... `cache_period` seems like a good addition.

2. My point was that it's erroneous for a new `validUntil` to **not** affect the `ETag` value, because the document has changed. That is to say: In the current implementation, if the federation data never changes, it would be completely valid for an IdP or SP to **never** download a new document even after the current one expires (because by definition the documents are considered equal if they have the same `ETag`).

    For a naïve caching SP/IdP which relies on `If-None-Match` to avoid downloading an unchanged document, it will never receive a response containing a metadata document with a new `validUntil` timestamp and will be knocked out of service. My understanding is that even after the cached document expires, the `ETag` of a newly generated one will be the same, so it'll still see a `304 Not Modified` response.

3. You're correct that this is addressed by expiring the cached content sooner, but particular care needs to be taken with `ETag` values. I wasn't suggesting that it should be client-driven, only that we do need to freshen the cached document even when things haven't changed.

4. Noted. I'm talking about valid HTTP client behaviour in the pathological case. It's only really a suggestion about improving behaviour in the worst conceivable case, and probably wouldn't have any impact in reality.

**Comment by bradleybeddoes** [comment]
With regards to #2 you're correct, this is a case which is not correctly handled.

I propose we alter https://github.com/ausaccessfed/saml-service/blob/develop/app/controllers/concerns/metadata_query_caching.rb#L28 to also check that the content still exists in the local cache e.g.

    Rails.cache.fetch(etag)   # !nil

That way once a generated document is evicted from cache (already keyed on etag), even if there has been no update to the internal objects a newer copy, thus a documented with an extended `validUntil` will have to be returned.
